### ISSUE TITLE
Error running bundle_dmg.sh

### ISSUE THREAD

**Issue by suptejas** [tauri-apps/tauri-action#1003]
```
    Bundling [tauri_bundler::bundle::macos::dmg] Dimension_0.0.1_aarch64.dmg (/Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Dimension_0.0.1_aarch64.dmg)
    Running [tauri_bundler::bundle::macos::dmg] bundle_dmg.sh
    Running [tauri_bundler::utils] Command `/Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/bundle_dmg.sh  --volname Dimension --icon Dimension.app 180 170 --app-drop-link 480 170 --window-size 660 400 --hide-extension Dimension.app --volicon /Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/icon.icns Dimension_0.0.1_aarch64.dmg Dimension.app`
Creating disk image...
created: /Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/rw.4679.Dimension_0.0.1_aarch64.dmg
Mounting disk image...
Device name:     /dev/disk3
Searching for mounted interstitial disk image using /dev/disk3s...
Mount dir:       /Volumes/dmg.PFfA56
Making link to Applications dir...
/Volumes/dmg.PFfA56
Copying volume icon file '/Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/icon.icns'...
Will sleep for 2 seconds to workaround occasions "Can't get disk (-1728)" issues...
Running AppleScript to make Finder stuff pretty: /usr/bin/osascript "/var/folders/gv/v8nf0hv14_d79wlg2q1j88j40000gn/T/createdmg.tmp.XXXXXXXXXX.IgG907SyqI" "dmg.PFfA56"
/var/folders/gv/v8nf0hv14_d79wlg2q1j88j40000gn/T/createdmg.tmp.XXXXXXXXXX.IgG907SyqI:394:406: execution error: Finder got an error: AppleEvent timed out. (-1712)
Failed running AppleScript
Unmounting disk image...
"disk3" ejected.
failed to bundle project: error running bundle_dmg.sh: `failed to run /Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/bundle_dmg.sh`
    Error [tauri_cli_node] failed to bundle project: error running bundle_dmg.sh: `failed to run /Users/runner/work/desktop/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/bundle_dmg.sh`
```

```yaml
- name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CI: true
        with:
          args: --target ${{ matrix.target }} --verbose
```

Any idea on what's causing this issue? Seems like it may be something for the setup of the dmg window?
