### ISSUE TITLE
x64 not built on macOS using example workflow

### ISSUE THREAD

**Issue by ok-nick** [tauri-apps/tauri-action#1050]
The README and docs [found here](https://v2.tauri.app/distribute/pipelines/github/#example-workflow), state to use the line below for `tauri-action`:
```
args: ${{ matrix.args }}
```

However, in the docs for macOS signing [here](https://v1.tauri.app/v1/guides/distribution/sign-macos/#example), it states to use:
```
args: ${{ matrix.settings.args }}
```

I found that if the second method isn't used, macOS will only build `aarch64` packages, even when this line is included:
```
- platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
```

TLDR; I believe the docs and example workflow should change to use:
```
args: ${{ matrix.settings.args }}
```

**Comment by FabianLars** [comment]
The v2 docs and this repo's readme and examples were updated to use a arguably better matrix. The v2 docs were updated in the main places as well, but it looks like we missed that one.

Either way, this action considers `matrix.args` correct which will require the matrix at the top to be
```yml
matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
...
```
instead of
```yml
matrix:
        settings:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
...
```
(only the include/settings line changes)

Your workflow for example (assuming we're talking about https://github.com/ok-nick/c2pa-preview/blob/main/.github/workflows/publish.yml) still uses the old syntax (which is fine, but means you'll need `matrix.settings.args`
