### ISSUE TITLE
v0.5.21: Signature not found for the updater JSON. Skipping upload...

### ISSUE THREAD

**Issue by rphovley** [tauri-apps/tauri-action#1098]
When running this action using the latest release, I get the following error
```
    Finished 1 updater signature at:
        /Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app.tar.gz.sig

Done in 150.09s.
Looking for artifacts in:
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Ebb_0.3.13_aarch64.dmg
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app.tar.gz
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app.tar.gz.sig
Found artifacts:
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Ebb_0.3.13_aarch64.dmg
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app.tar.gz
/Users/runner/work/ebb-app/ebb-app/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Ebb.app.tar.gz.sig
Found release with tag v0.3.13.
Deleting existing Ebb_0.3.13_aarch64.dmg...
Uploading Ebb_0.3.13_aarch64.dmg...
Signature not found for the updater JSON. Skipping upload...
```
The latest.json artifact is not uploaded with the .dmg resulting in errors from the application as it tries to update.

When reverting back to v0.5.20, the latest.json artifact is uploaded as expected along with the .dmg files

**Comment by FabianLars** [comment]
Can you share your workflow as well? The tauri-action step should be enough.

**Comment by rphovley** [comment]
Here's what I have
```
 - name: build and publish
        uses: tauri-apps/tauri-action@v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_PATH: ~/private_keys/AuthKey.p8
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ env.VERSION }}
          ...other environment variables
        with:
          tagName: v__VERSION__
          releaseName: "v__VERSION__"
          releaseBody: |
            Changes in this Release:

            ${{ steps.create_changelog.outputs.changelog }}
          args: ${{ matrix.args }}
          includeUpdaterJson: true
```

**Comment by FabianLars** [comment]
thanks

**Comment by FabianLars** [comment]
0.5.22 released with the fix

**Comment by rphovley** [comment]
Thank you!

**Comment by jacek-kurlit** [comment]
Hello,
Sorry for writing in closed issue but I still have this issue despite using latest version
```
 Looking for artifacts in:
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/deb/vat-hub_0.1.0_amd64.deb
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/rpm/vat-hub-0.1.0-1.x86_64.rpm
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/appimage/vat-hub_0.1.0_amd64.AppImage
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/appimage/vat-hub_0.1.0_amd64.AppImage.sig
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/appimage/vat-hub_0.1.0_amd64.AppImage.tar.gz
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/appimage/vat-hub_0.1.0_amd64.AppImage.tar.gz.sig
Found artifacts:
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/deb/vat-hub_0.1.0_amd64.deb
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/rpm/vat-hub-0.1.0-1.x86_64.rpm
/home/runner/work/vat-hub/vat-hub/src-tauri/target/release/bundle/appimage/vat-hub_0.1.0_amd64.AppImage
Looking for a draft release with tag app-v0.1.0...
Found draft release with tag app-v0.1.0 on the release list.
Deleting existing vat-hub_0.1.0_amd64.deb...
Uploading vat-hub_0.1.0_amd64.deb...
Deleting existing vat-hub-0.1.0-1.x86_64.rpm...
Uploading vat-hub-0.1.0-1.x86_64.rpm...
Deleting existing vat-hub_0.1.0_amd64.AppImage...
Uploading vat-hub_0.1.0_amd64.AppImage...
Signature not found for the updater JSON. Skipping upload...
```
This is my config
```yml
      - uses: tauri-apps/tauri-action@v0.5.22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
```

**Comment by FabianLars** [comment]
@jacek-kurlit you don't have tauris updater configured. If you don't set `createUpdaterArtifacts: true` in tauri.conf.json tauri will not generate signatures.

**Comment by jacek-kurlit** [comment]
Ok I have added this to tauri.conf.json `Signature not found for the updater JSON. Skipping upload...` still remains though but it only means that no updater json will be uploaded right? My problem is that I don't see any file uploaded to GitHub Release

**Comment by jacek-kurlit** [comment]
Ok I'm dumb. This must be set to `releaseDraft: false` 
Now everything is ok.
Sorry for the trouble

**Comment by lanxiuyun** [comment]
Really Really Sorry for writing in closed issue but I still have this issue despite using latest version.

I don't know why the Windows release message can be generated in the latest.json but the Mac can not.
Here is my workflow
```
      - uses: tauri-apps/tauri-action@v0
        id: tauri-action # 添加 id 以便后续引用
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false # 不创建草稿版本
          prerelease: false # 不作为预发布版本
          args: ${{ matrix.args }}
```
And the release
https://github.com/lanxiuyun/lazyeat/releases/tag/v1.0.1

<img width="3092" height="1453" alt="Image" src="https://github.com/user-attachments/assets/0e56bb19-f3e1-4aa1-a76c-fef593e3adc4" />
