### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aafnnp** [tauri-apps/tauri-action#113]
running tauri build
[tauri]: running build
 ERROR: tauri.conf.json > tauri has unknown property updater +0ms
 ERROR: tauri.conf.json > tauri has unknown property windows +1ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property macOS +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property windows +0ms
this
Error: Command failed with exit code 1: tauri build

**Comment by nothingismagick** [comment]
This is because the wrong version of tauri is being used (the alpha version).

**Comment by aafnnp** [comment]
> This is because the wrong version of tauri is being used (the alpha version).

updated latest tauri-cli today.

so when and how to fix this problem

**Comment by nothingismagick** [comment]
Can you provide a repo where we can review your implementation please?

**Comment by aafnnp** [comment]
> Can you provide a repo where we can review your implementation please?

https://github.com/Manonicu/remix

**Comment by nothingismagick** [comment]
This, I am assuming:
https://github.com/Manonicu/remix/blob/dev/src-tauri/Cargo.toml

**Comment by nothingismagick** [comment]
Well this is the problem:
https://github.com/Manonicu/remix/runs/2446458450?check_suite_focus=true#step:8:7

**Comment by aafnnp** [comment]
> Well this is the problem:
> https://github.com/Manonicu/remix/runs/2446458450?check_suite_focus=true#step:8:7

yes

**Comment by nothingismagick** [comment]
Because it should be this:
https://github.com/tauri-apps/tauri-action/blob/b87425614119f70be189fddd40a403481b91a328/packages/core/index.ts#L84

**Comment by nothingismagick** [comment]
So my guess is that we just need to release a new version for you - will wait for @lucasfernog to get in and confirm though.

And on a sidenote, please bear with us - the Tauri Beta is still a release candidate, which means we actually have bigger priorities to make sure core is working. The tauri-action is important, but a bit lower on our list of priorities. Thanks for understanding.

**Comment by aafnnp** [comment]
> Because it should be this:
> https://github.com/tauri-apps/tauri-action/blob/b87425614119f70be189fddd40a403481b91a328/packages/core/index.ts#L84

dev branch

**Comment by aafnnp** [comment]
> So my guess is that we just need to release a new version for you - will wait for @lucasfernog to get in and confirm though.
> 
> And on a sidenote, please bear with us - the Tauri Beta is still a release candidate, which means we actually have bigger priorities to make sure core is working. The tauri-action is important, but a bit lower on our list of priorities. Thanks for understanding.

got it,wait for release

**Comment by nothingismagick** [comment]
or use the dev branch to test it out:
```
      - uses: tauri-apps/tauri-action@dev
```

**Comment by lucasfernog** [comment]
I'm just fixing a minor issue here and then I'll release it. Sorry for the delay but we had more important issues to fix on the core packages.

**Comment by aafnnp** [comment]
> I'm just fixing a minor issue here and then I'll release it. Sorry for the delay but we had more important issues to fix on the core packages.

which branch or version

fix/ci?

**Comment by jbolda** [comment]
> > I'm just fixing a minor issue here and then I'll release it. Sorry for the delay but we had more important issues to fix on the core packages.
> 
> which branch or version
> 
> fix/ci?

Aye, that is correct.

**Comment by aafnnp** [comment]
``` yaml
name: "test"
on:
  push:
    branches:
      - dev

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install tauri bundler
        run: cargo install tauri-bundler --force
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

![image](https://user-images.githubusercontent.com/12791216/116494878-5bb42d80-a8d4-11eb-9d3a-9c88567be4bc.png)
