### ISSUE TITLE
Add debug input to workflow

### ISSUE THREAD

**Issue by danielvschoor** [tauri-apps/tauri-action#131]
The ability to build debug builds would improve the build times on workflows that just checks if a commit still compiles.

**Comment by lucasfernog** [comment]
The scope of ths action is for publishing workflows but i've added this anyway, it's a good addition. Now you can do this on your workflow:

```yml
- uses: tauri-apps/tauri-action@v0
  with:
    args: --debug
```
