### ISSUE TITLE
Ignores `draft` option

### ISSUE THREAD

**Issue by lukeed** [tauri-apps/tauri-action#148]
While releasing, using this config block immediately creates a public release instead of a release draft

```yaml
    - name: Tauri Build
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # NOTE: "__VERSION__" automatically replaced
        tagName: v__VERSION__
        releaseName: v__VERSION__
        body: "See the assets to download this version and install."
        prerelease: false
        draft: true
```

Also, it seems like the `body` is ignored too. 
This is what a release looks like upon completion:

<img width="505" alt="Screen Shot 2021-06-21 at 4 52 26 PM" src="https://user-images.githubusercontent.com/5855893/122841932-2fec6d00-d2b1-11eb-89c4-2d1addad0119.png">
