### ISSUE TITLE
how can I use tauri-action in my tauri project?

### ISSUE THREAD

**Issue by turbodblabs** [tauri-apps/tauri-action#170]

**Comment by liudonghua123** [comment]
I use this github action to build a simple app, you can view my workflow file.

  ```
  name: 'publish'
  on:
    push:
      branches:
        - '*'
      tags:
        - '*'
  
  jobs:
    publish-tauri:
      permissions:
        contents: write
      strategy:
        fail-fast: false
        matrix:
          platform: [macos-latest, ubuntu-20.04, windows-latest]
  
      runs-on: ${{ matrix.platform }}
      steps:
        - uses: actions/checkout@v3
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: install Rust stable
          uses: dtolnay/rust-toolchain@stable
        - name: install dependencies (ubuntu only)
          if: matrix.platform == 'ubuntu-20.04'
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        - name: install frontend dependencies
          run: |
            npm install
            npm run build
        - uses: tauri-apps/tauri-action@v0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            distPath: ../build
            args: -c {"package":{"version":"${{ github.ref_name }}"},"tauri":{"bundle":{"identifier":"com.scratch.app"}}}
            tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
            releaseName: 'App v__VERSION__'
            releaseBody: 'See the assets to download this version and install.'
            releaseDraft: false
            prerelease: false
  ```
https://github.com/liudonghua123/scratch-gui/blob/develop/.github/workflows/publish.yml

Some of the shortcoming are:

1. you can not deploy the executables like `app.exe` or `app`.
2. some targets are not support default, like windows 32-bit, linux 32-bit targets.
