### ISSUE TITLE
Code signing on macOS fails.

### ISSUE THREAD

**Issue by sprout2000** [tauri-apps/tauri-action#234]
I got the following error message:

```sh
[tauri:build] Binary stripped, size reduced by 1.69 MB
    Bundling gh-action-tauri.app
info: setup keychain from environment variables...
Error running CLI: failed to bundle project: failed to import keychain certificate Ok(""): failed to import keychain certificate Ok("")
Error: Command failed with exit code 1: npx tauri build
```

`.github/workflows/publish.yml`:

```yml
name: 'publish'
on:
  push:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install app dependencies and build it
        run: npm i
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_IDENTITY_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
```

my actions secrets:

```sh
APPLE_SIGNING_IDENTITY="Developer ID Application: **** ******* (***FKK**3B)"
APPLE_CERTIFICATE="AgEAMIIGxQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYw ~ C2PDAn=="
APPLE_CERTIFICATE_PASSWORD="************"
APPLE_ID="foobar@example.com"
APPLE_PASSWORD="*my*-*app-spec-pswd"
```
