### ISSUE TITLE
Tauri "Uploading the artifacts to a release" failing even though it worked before

### ISSUE THREAD

**Issue by p32929** [tauri-apps/tauri-action#259]
Hello, I've used this code from this repo:
```
name: "release"
on:
    pull_request:
        branches:
            - master

env:
  CI: false

jobs:
    create-release:
        runs-on: ubuntu-latest
        outputs:
            RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: get version
              run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
            - name: create release
              id: create_release
              uses: actions/create-release@v1.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.PACKAGE_VERSION }}
                  release_name: "Remix v${{ env.PACKAGE_VERSION }}"
                  body: CHANGELOG.md
                  draft: false
                  prerelease: false
    build-tauri:
        needs: create-release
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install tauri bundler
              run: cargo install tauri-bundler --force
            - name: install webkit2gtk libgtk-3-dev libappindicator3-dev (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webkit2gtk-4.0 libgtk-3-dev libappindicator3-dev
            - name: install app dependencies and build it
              run: npm install && npm run build
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
```

( I have only added `CI: false` as it was failing otherwise )
& it worked before. But nor sure what happened later, it keeps on showing these errors:

![Screenshot (6)](https://user-images.githubusercontent.com/6418354/164619366-4bd9d438-0531-4e8d-944b-800b5b010eb0.png)
![Screenshot (7)](https://user-images.githubusercontent.com/6418354/164619373-ce9ea1d9-a51b-4bbc-8b6b-9c28fdfd88f9.png)

I'm not sure if the error is from github action itself or the code. 

Thanks
