### ISSUE TITLE
Failed to bundle project: error running candle.exe

### ISSUE THREAD

**Issue by KillerCodeMonkey** [tauri-apps/tauri-action#265]
Hey there,

two days ago building tauri for win64 on github works like charme.
But since yesterday evening i get:

```sh
Finished release [optimized] target(s) in 16m 58s
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
        Info validating hash
        Info extracting WIX
        Info Target: x64
     Running candle for "main.wxs"
failed to bundle project: error running candle.exe: error running candle.exe: ``
```

Seems like this occurs even when directly running "tauri build".

Any ideas?

**Comment by lucasfernog** [comment]
Please try running with --verbose so we can see what's wrong.

**Comment by KillerCodeMonkey** [comment]
since i have no windows computer and only building it in ci. it is possible to add the verbose flag to the tauri github action? If not i will replace using the action with just a build command

**Comment by KillerCodeMonkey** [comment]
ahhh it looks like my dev-builds are letting the build fail.

so i have nightly, alpha beta releases and seems like wix only supports versions ins format x.x.x.x sadly. So my e.g. 0.1.0-beta.1 is not working. :(

**Comment by FabianLars** [comment]
Yep, wix only supports numeric versions, so there's nothing we can do here :/

> it is possible to add the verbose flag to the tauri github action?

Yeah it has a undocumented `args` property, so you can add `args: '--verbose'` and it should work.

**Comment by KillerCodeMonkey** [comment]
nice and thanks for your blazing fast response. 

I added some additional info to the title.
If anybody is stumbling with semver + special channels in versions my solution is to just use https://github.com/actions/github-script and make some little string replacements and after that setting a "cleaned" version in the tauri.conf.json.

In general i came to this, because of this bug: https://github.com/tauri-apps/tauri-action/issues/262

I wanted to get my version from package.json in the tauri.conf.json during build. So i added the package.json path in the tauri config for the version field. But it does not work with the github action.

I ended in something like that:

```yml
jobs:
  ...

  build-windows:
    needs: [create-release]

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      ...

      - uses: actions/github-script@v6
        id: get-wix-compatible-version
        env:
          VERSION: ${{needs.create-release.outputs.version}}
        with:
          result-encoding: string
          script: |
            return process.env.VERSION.replace(/-.*(\.\d+)$/, '$1').replace(/^v/, '')
      - name: Fix version in tauri.config | https://github.com/tauri-apps/tauri-action/issues/262
        run: |
          npm i --save-dev replace-in-file
          npx replace-in-file ../package.json ${{steps.get-wix-compatible-version.outputs.result}} src-tauri\tauri.conf.json

       ...
```

The script replaces additional suffixes at the version, but requires that those nightly, beta, what ever version end with `.[0-9]+`, so we get a valid fourth place in the wix version.

if you have a "tag" as version then remove the leading "v" in the version

E.g. Version v1.2.3-lorem-ipsum.4 gets to 1.2.3.4

Greetings :)
