### ISSUE TITLE
How to use this with yew

### ISSUE THREAD

**Issue by arlyon** [tauri-apps/tauri-action#307]
Hello

It's not quite clear how to use this in a non-yarn workflow (yew). I am using a slightly modified version of the last workflow since this action does not download trunk. Do we need to build the app before running the action? Do we do that with `cargo tauri build` or just with `cargo build`?

Guidance appreciated.

Thanks!

**Comment by FabianLars** [comment]
tauri-action invokes `cargo tauri build` for you. If your beforeBuildCommand builds your yew frontend (or in other words: if `cargo tauri build` is the only thing you need on your local machine to get a bundled app), you should be good to go already.

Otherwise you could indeed just build your frontend separately before the tauri-action step 🤷

**Comment by arlyon** [comment]
After a bit of experimenting I found a combo that works :) I will open a PR, if you'd like to add to the readme. TY for the help.

**Comment by FabianLars** [comment]
That depends on how large the solution is i guess. Becuase yew still is still not _that_ popular, i'd rather not bloat the readme with something most won't use/understand.

Anyway, I thought about having an example folder in the repo, but i'm not 100% sure yet (wouldn't be worth it if there's just one example). Can you just post the relevant code here? Should be enough visibility for now.

**Comment by bicarlsen** [comment]
@arlyon , could you post the solution you arrived at?

**Comment by arlyon** [comment]
@bicarlsen 

```yaml
  build-tauri:
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-20.04

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.1.0
        with:
          # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
          version: "latest"
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: build in release mode
        run: cargo build --release
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
```
