### ISSUE TITLE
Automatic Ubuntu dependency installation

### ISSUE THREAD

**Issue by kasper9n** [tauri-apps/tauri-action#334]
Just noticed that the Ubuntu install command is different than what it was before:
```yml
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
```

It would be great if the tauri action could take care of that step automatically by default. If the command needs to be changed in the future, it could be included in a major version update
