### ISSUE TITLE
Support platform-specified configuration.

### ISSUE THREAD

**Issue by importcjj** [tauri-apps/tauri-action#337]
I added a new configuration file `tauri.linux.conf.json`  for my Linux app,  which has a different `productName` , But when this action runs, it returns an error message:

```
    Finished release [optimized] target(s) in 8m 17s
    Bundling terminal_0.6.0_amd64.deb (/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/deb/terminal_0.6.0_amd64.deb)
    Bundling terminal_0.6.0_amd64.AppImage (/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage)
    Bundling /home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage.tar.gz (/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage.tar.gz)
    Finished 3 bundles at:
        /home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/deb/terminal_0.6.0_amd64.deb
        /home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage
        /home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage.tar.gz (updater)

        Info 1 updater archive at:
        Info         /home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/terminal_0.6.0_amd64.AppImage.tar.gz.sig
Expected artifacts paths:
/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/deb/智堡终端_0.6.0_amd64.deb
/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/智堡终端_0.6.0_amd64.AppImage
/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/智堡终端_0.6.0_amd64.AppImage.tar.gz
/home/runner/work/wisburg-terminal/wisburg-terminal/src-tauri/target/release/bundle/appimage/智堡终端_0.6.0_amd64.AppImage.tar.gz.sig
Error: No artifacts were found.
```

It seems this action doesn't recognize the Linux configuration file, and just uses the old product name that is in the main configuration file.

**Comment by calebsmithdev** [comment]
I am having a similar issue on the mac side where I am trying to compile a Silicon and an Intel version. Here is the output after targeting the silicon target directly:

```
    Finished 3 bundles at:
Password: <empty>
        /Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Wowthing Sync.app
        /Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Wowthing Sync_0.1.9_aarch64.dmg
        /Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Wowthing Sync.app.tar.gz (updater)

Deriving a key from the password and decrypting the secret key... done
        Info 1 updater archive at:
        Info         /Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Wowthing Sync.app.tar.gz.sig
Done in 519.41s.
Expected artifacts paths:
/Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/release/bundle/dmg/Wowthing Sync_0.1.9_x64.dmg
/Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/release/bundle/macos/Wowthing Sync.app
/Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/release/bundle/macos/Wowthing Sync.app.tar.gz
/Users/runner/work/wowthing-sync/wowthing-sync/src-tauri/target/release/bundle/macos/Wowthing Sync.app.tar.gz.sig
```

My action runner step for reference:
```
      - name: 'Build the Mac Silicon version'
        if: matrix.platform == 'macos-12'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          releaseId: ${{ env.RELEASE_ID }}
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: --target aarch64-apple-darwin
```
