### ISSUE TITLE
enhancement: option to upload artifact on ci workflow

### ISSUE THREAD

**Issue by Ludea** [tauri-apps/tauri-action#342]
For now I use https://github.com/actions/upload-artifact to do the job.

It can be usefull to add an option to do the same thing.  

WDYT ?

**Comment by FabianLars** [comment]
Since this is probablyyy a niche feature, i think i'd prefer if the action would output the paths of the generated bundles instead. This would be way more flexible and could cover more use cases. any thoughts about that?

**Comment by Ludea** [comment]
it's an alternative solution, why not

**Comment by Ludea** [comment]
I reopen, because after some thoughts, I would like to add short commit into assets name, to avoid confusion with release assets

**Comment by septum** [comment]
This is slightly related, but seems like a good place to ask this: Do the artifacts stick around after the action ends? I ask this because we are having trouble sending them to an S3 bucket, with the error output stating that the path does not exist.

**Comment by FabianLars** [comment]
Yes they do, but only for the following steps of the current jobs, other jobs won't have access to it.
Also, the action will return the paths of the artifacts as a json string which you may be able to use (though if you know your project the paths are pretty easy to predict).

**Comment by xstevenyung** [comment]
i'm not sure this is that niche of a use-case, not a lot of private repos are going to use the github releases for their apps. 

maybe a good compromise would be to include a way to upload to different provider in the docs? it's pretty hard at the moment to find information on how to set things up so having more documentation directly in the README could help immensely

**Comment by martpie** [comment]
I would like to second the ability to upload artifacts without having to rely on releases. I very frequently build all binaries as part of a PR, and it is really nice to be able to go to a run artifacts section and download binaries from there (for testers, etc).

Example: https://github.com/martpie/museeks/actions/runs/8484717113

![image](https://github.com/tauri-apps/tauri-action/assets/1311607/a4b303a4-0a8b-4dda-b8b1-30a2c60fd5fb)

**Comment by brianz** [comment]
For anyone who comes here looking to upload artifacts to other locations, here is how I solved it to upload to S3.

It's fairly simple once you understand that the `artifactPaths` is json-encoded array of absolute file paths. In any subsequent upload step, you need to decode it and then upload each item. As seen below, you can do this using `jq` which is available by default.

This also becomes trickier with Windows builds that output paths like `D:\\a\\myapp-sveltekit\\myapp-sveltekit\\src-tauri\\target\\release\\bundle\\msi\\MyApp_5.0.3_x64_en-US.msi`. ChatGPT gave me the solution using Powershell which worked on the first try. 

```yaml
      - uses: tauri-apps/tauri-action@v0
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

        with:
          # Comment out tagName and releaseName to prevent automatically uploading to GH
          # tagName: myapp-v__VERSION__ 
          # releaseName: 'MyApp v__VERSION__'
          includeUpdaterJson: false
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeDebug: true
          args: ${{ matrix.settings.args }}

      - name: Upload artifacts to AWS S3
        if: matrix.settings.platform == 'macos-latest'
        run: |
          paths=$(echo '${{ steps.build.outputs.artifactPaths }}' | jq -c '.[]' | sed 's/"//g')
          for fn in $paths; do
            if [[ -f $fn ]]; then
              echo "Uploading $fn"
              aws s3 cp $fn s3://myBucketName/
            fi
          done

      - name: Upload artifacts to AWS S3 (Windows)
        if: matrix.settings.platform == 'windows-latest'
        shell: pwsh
        run: |
          $jsonString = '${{ steps.build.outputs.artifactPaths }}'
          $filePaths = ConvertFrom-Json $jsonString
          foreach ($path in $filePaths) {
            if (Test-Path $path -PathType Leaf) {
              Write-Host "Uploading $path"
              aws s3 cp $path s3://myBucketName/
            }
```
