### ISSUE TITLE
tauri-action@v0.2.0 does not find a Windows build

### ISSUE THREAD

**Issue by andeke07** [tauri-apps/tauri-action#348]
tauri-apps/tauri-action@v0.2.0 does not seem to find a Windows build to upload (but completes with MacOS/Ubuntu). When running tauri-action@v0 the build completes and is uploaded to my release. My Action file (which I basically just copied from the sample one):

```yaml
name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-12, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          touch .env
          echo PARAM=blah >> .env
  
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.0

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: npm install

      - name: Build and release
        uses: tauri-apps/tauri-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
```

Both the macOS and Ubuntu versions create an executable, but the windows-latest runner does not:

```
Running light to produce D:\a\memedia-tauri\memedia-tauri\src-tauri\target\release\bundle/msi/memedia-gsync_1.0.0_x64_en-US.msi
[649](https://github.com/andeke07/memedia-tauri/actions/runs/3788758040/jobs/6441859015#step:8:650)
    Finished 1 bundle at:
[650](https://github.com/andeke07/memedia-tauri/actions/runs/3788758040/jobs/6441859015#step:8:651)
        D:\a\memedia-tauri\memedia-tauri\src-tauri\target\release\bundle/msi/memedia-gsync_1.0.0_x64_en-US.msi
[651](https://github.com/andeke07/memedia-tauri/actions/runs/3788758040/jobs/6441859015#step:8:652)

[652](https://github.com/andeke07/memedia-tauri/actions/runs/3788758040/jobs/6441859015#step:8:653)
Error: No artifacts were found.
```

If I change the Build and Release stage to use `tauri-apps/tauri-action@v0` it works.
