### ISSUE TITLE
Error: No artifacts were found.

### ISSUE THREAD

**Issue by zh30** [tauri-apps/tauri-action#356]
I added `ages:-target universal-apple-darwin` to TAURI-APPS/TAURI-ACTION@V0, and the build went smoothly, but at the end there was an Error: `Error: No artifacts were found.`
How can I solve such a problem.
Thanks

```yml
        - name: Build the app (macOS only)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          args: --target universal-apple-darwin
          releaseName: 'Eventloop Todo ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          # releaseDraft: true
          prerelease: true
```

```
Finished release [optimized] target(s) in 2m 57s
    Bundling EventLoop Todo.app (/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/universal-apple-darwin/release/bundle/macos/EventLoop Todo.app)
    Bundling EventLoop Todo_0.0.6_universal.dmg (/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/universal-apple-darwin/release/bundle/dmg/EventLoop Todo_0.0.6_universal.dmg)
     Running bundle_dmg.sh
    Finished 2 bundles at:
        /Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/universal-apple-darwin/release/bundle/macos/EventLoop Todo.app
        /Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/universal-apple-darwin/release/bundle/dmg/EventLoop Todo_0.0.6_universal.dmg

Expected artifacts paths:
/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/release/bundle/dmg/EventLoop Todo_0.0.6_x64.dmg
/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/release/bundle/macos/EventLoop Todo.app
/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/release/bundle/macos/EventLoop Todo.app.tar.gz
/Users/runner/work/eventloop-todo-app/eventloop-todo-app/src-tauri/target/release/bundle/macos/EventLoop Todo.app.tar.gz.sig
Error: No artifacts were found.
```
