### ISSUE TITLE
Input required and not supplied: path

### ISSUE THREAD

**Issue by linonetwo** [tauri-apps/tauri-action#384]
With

```yaml
      - name: Upload to release on git tag Or output artifact path on nightly
        uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tauri-client-app-artifact
          path: ${{ steps.tauri-action.outputs.artifactPaths }}

```

I get https://github.com/toeverything/AFFiNE/actions/runs/4172597883/jobs/7224043248

```
...
Expected artifacts paths:
D:\a\AFFiNE\AFFiNE\apps\desktop\src-tauri\target\release\bundle\msi\AFFiNE_0.0.2_x64_en-US.msi
D:\a\AFFiNE\AFFiNE\apps\desktop\src-tauri\target\release\bundle\msi\AFFiNE_0.0.2_x64_en-US.msi.zip
D:\a\AFFiNE\AFFiNE\apps\desktop\src-tauri\target\release\bundle\msi\AFFiNE_0.0.2_x64_en-US.msi.zip.sig
Artifacts: D:\a\AFFiNE\AFFiNE\apps\desktop\src-tauri\target\release\bundle\msi\AFFiNE_0.0.2_x64_en-US.msi.

x Upload Artifact
Run actions/upload-artifact@v3
Error: Input required and not supplied: path
```

**Comment by FabianLars** [comment]
you'll probably need something like this
```yml
path: |
  ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[0] }}
  ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[1] }}
  ${{ fromJSON(steps.tauri-action.outputs.artifactPaths)[2] }}
```
the upload-artifacts action can't decode a json array by itself automatically

~~Edit: actuallyyy, another thing. artifactPaths is only available in `tauri-action@dev` right now (the point above still stands tho)~~ It was released as part of v0.4

**Comment by linonetwo** [comment]
Thanks, I'm trying, but can we be sure there will be at most 3 artifacts?

**Comment by FabianLars** [comment]
_currently_ that depends on the platform and the config. on windows it will always be 3 unless you build multiple WiX languages, or enable the debug build. This will increase in tauri 1.3 with the new nsis target. On macos and linux it will be 4 by default.

Sooo, you're probably better of not using these paths at all (unless you want to add a really long list) and instead use wildcard patterns to match `.AppImage`, `.AppImage.tar.gz`, `.deb`, `.msi`, `.msi.zip` `.app.tar.gz` files and their `.sig` files in the target dir :/

Or maybe add another step in between where you clean unwanted files from the `target/bundle/` dir, or consume the artifactPaths input and move all the actual artifacts to a common location, idk.

**Comment by linonetwo** [comment]
Thank you, you are very helpful. I think the problem is solved.

**Comment by martpie** [comment]
To folks interested, here's how I've done it:

```yaml
      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: binaries-linux
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.deb
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.rpm
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.AppImage

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: binaries-macos
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.dmg

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: binaries-windows
          path: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/**/*.exe
```

This requires maintaining the list of extensions/targets by yourself, but I prefer that over the `fromJSON` thing.
