### ISSUE TITLE
MacOS untrusted?

### ISSUE THREAD

**Issue by MrMarble** [tauri-apps/tauri-action#463]
I have setup the action to bundle for ubuntu, windows and macOS usin the `dev` tag.

When installing the app I get this message saying that the developer is not trusted, do I really need to pay 99$ a year to have my app working on Mac? or I missed some configuration?

<img width="420" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/4268580/af3e0194-91b7-4c5c-be93-7271fb722db8">

Here's my workflow file and my tauri config:

<details><summary>Workflow</summary>

```yaml
name: "publish"

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.PACKAGE_VERSION}`,
              name: `XEID v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install this app.',
              draft: true,
              prerelease: false
            })
            return data.id

  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm" # Set this to npm, yarn or pnpm.

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ""
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "XEID v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [create-release, build-tauri]

    steps:
      - name: publish releasez
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
```

</details> 

<details><summary>Tauri config</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/tauri-apps/tauri/dev/tooling/cli/schema.json",
  "build": {
    "beforeDevCommand": "pnpm run dev",
    "beforeBuildCommand": "pnpm run build",
    "devPath": "http://localhost:5173",
    "distDir": "../src/dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "XEID",
    "version": "../package.json"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "os":{
        "all": true
      },
      "shell": {
        "all": false,
        "open": true
      },
      "window": {
        "all": false,
        "close": true,
        "hide": true,
        "show": true,
        "maximize": true,
        "minimize": true,
        "unmaximize": true,
        "unminimize": true,
        "startDragging": true
      },
      "fs": {
        "all": false,
        "copyFile": false,
        "createDir": false,
        "exists": false,
        "readDir": false,
        "readFile": true,
        "removeDir": false,
        "removeFile": true,
        "renameFile": false,
        "scope": [
          "$APPDATA/",
          "$APPDATA/**"
        ],
        "writeFile": true
      }
    },
    "bundle": {
      "active": true,
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "app.xeid.mrmarble",
      "targets": "all",
      "category": "DeveloperTool",
      "windows": {
        "allowDowngrades": true,
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": null,
        "tsp": false,
        "webviewFixedRuntimePath": null,
        "webviewInstallMode": {
          "silent": true,
          "type": "downloadBootstrapper"
        },
        "wix": {}
      },
      "appimage": {
        "bundleMediaFramework": false
      },
      "macOS": {
        "minimumSystemVersion": "10.13",
        "license": "../LICENSE"
      },
      "deb": {
        "files": {}
      },
      "copyright": "Copyright (c) 2023 Alvaro Tinoco",
      "shortDescription": "eXecution Environment IDE"
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": true,
      "dialog": true,
      "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDlDRjY2QjY5RERGMTIzNzIKUldSeUkvSGRhV3YybkltdERpY2ZzMlhQdi9XZXpodFNWa3ZFaDFUTCtRc2JEbE9kTWVWUTZtc0EK",
      "windows": {
        "installMode": "passive"
      },
      "endpoints": [
        "https://github.com/mrmarble/xeid/releases/latest/download/latest.json"
      ]
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "XEID",
        "width": 1000,
        "height": 600,
        "visible": false,
        "decorations": false
      }
    ]
  }
}
```

</details> 

Thank you
