### ISSUE TITLE
How to publish releases from one repository to another

### ISSUE THREAD

**Issue by nikivdev** [tauri-apps/tauri-action#473]
I have a private repository with this github action file content:

```yml
name: "tauri-release"
on:
  push:
    branches:
      - tauri-release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
      - name: Install dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          owner: "kuskusapp"
          repo: "kuskus"
          releaseCommitish: "94bc1cc4cb560e91583d530683f55c48c3fc6eec"
```

The private repo is kuskusapp/code. The release I want to publish is on https://github.com/kuskusapp/kuskus

Above action should in theory take care of this with this addition:

```
          owner: "kuskusapp"
          repo: "kuskus"
          releaseCommitish: "94bc1cc4cb560e91583d530683f55c48c3fc6eec"     
```

However I get this error:

<img width="1058" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/ae2e8d25-308c-46d6-861d-2bd8605d3430">

And I don't know how to get around it. 

I tried to even create a personal access token with these permissions 

<img width="829" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/23ecebdf-97b4-468d-9b4f-414cb6e8bfce">

<img width="797" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/09ecd796-a3e1-499f-8e54-cd27ed502e1f">

<img width="790" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/556e6bb6-0b66-4873-9eea-f143c79b876f">

Then try to put that token in secrets

<img width="317" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/d3f7a093-c13d-4134-868b-6ceee70065cc">

But it failed

<img width="514" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/efcc1975-685c-4cb2-ae0a-a92f8063f7f0">

Not sure what else to do. The 2 repos are on the same organisation. Just one is private repo but I want the releases to be on the public repo.

Thank you.

**Comment by nikivdev** [comment]
@FabianLars had the idea to rename the personal token to not start with `github_` but even then it failed.

Unless I have not used some right scopes for it.

<img width="1006" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/6391776/accd0c7e-5233-499c-9dc6-c77892a7e529">

**Comment by FabianLars** [comment]
Small update from [Discord](https://discord.com/channels/616186924390023171/1109608182499774596): The issue is that the target repo is in an org and not the personal account.
A "classic" PAT worked for me to upload it in an organization while beta PATs didn't. So that's a potential solution here, but looks like GitHub prefers setting up a "GitHub App" for this.

Anyway, going to close this then.

**Comment by maddybo** [comment]
@nikitavoloboev You find solution

**Comment by CallMeLaNN** [comment]
FYI I can publish releases to repo under organization from personal account. It is required to properly set token, permission and `releaseCommitish`.  I use fine-grained permission, just read and write for "contents".

```log
Error: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"} - https://docs.github.com/rest/releases/releases#create-a-release
```

I was looking for this error. I believe it default to `SHA of current commit` which is invalid SHA on the current repo. I have to explicitly set `releaseCommitish: main` in my case.

---

BTW, Don't use `GITHUB_`, some example come with GH_PAT or any name. So just put this `GITHUB_TOKEN: ${{ secrets.GH_PAT_RELEASE }}`

<details><summary>Example</summary>

```yaml
  steps:
      - name: Build Tauri and Publish Release Draft
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_RELEASE }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          # Build Options
          updaterJsonPreferNsis: true
          tauriScript: pnpm tauri

          # Release Configuration
          # the action automatically replaces \_\_VERSION\_\_ with the app version.
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "Release details"
          releaseDraft: true
          prerelease: false
          releaseCommitish: main
          owner: an-org
          repo: my-repo
```

</details>
