### ISSUE TITLE
Failed to resolve Tauri path when using this action

### ISSUE THREAD

**Issue by liudonghua123** [tauri-apps/tauri-action#477]
Hi, I have some static deployable ready files and I want to use `tauri-apps/tauri-action@v0` to build some executables. The project does not have `package.json` nor `src-tauri`. 

I have some action steps like this in my workflow.

```yml
      - uses: tauri-apps/tauri-action@v0
        name: package and deploy app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distPath: ${{env.JEKYLL_BUILD_DIR}}
          tagName: ${{env.APP_NAME}} v__VERSION__
          releaseName: "flutter.dev site v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          bundleIdentifier: dev.flutter.site
          args: -c {"build":{"beforeBuildCommand":""},"package":{"productName":"${{env.APP_NAME}}","version":"${{env.RELEASE_VERSION}}"}}
          releaseDraft: false
          prerelease: false
```

When running with github runner, I got the following errors.

```
Run tauri-apps/tauri-action@v0
  with:
    distPath: _site
    tagName: flutter_website v__VERSION__
    releaseName: flutter.dev site v__VERSION__
    releaseBody: See the assets to download this version and install.
    bundleIdentifier: dev.flutter.site
    args: -c {"build":{"beforeBuildCommand":""},"package":{"productName":"flutter_website","version":"3.10.0"}}
    releaseDraft: false
    prerelease: false
    projectPath: .
    includeDebug: false
    includeRelease: true
    includeUpdaterJson: true
    updaterJsonKeepUniversal: false
  env:
    NODE_ENV: production
    NODE_VERSION: 18
    APP_NAME: flutter_website
    RELEASE_VERSION: 3.10.0
    JEKYLL_BUILD_DIR: _site
    GITHUB_TOKEN: ***
running npm [ 'install', '-g', '@tauri-apps/cli' ]

added [2](https://github.com/liudonghua123/flutter_website/actions/runs/5076936604/jobs/9119740769#step:10:2) packages in [3](https://github.com/liudonghua123/flutter_website/actions/runs/5076936604/jobs/9119740769#step:10:3)s

1 package is looking for funding
  run `npm fund` for details
running tauri [ 'init', '--ci', '--app-name', 'docs.flutter.dev' ]
Failed to resolve Tauri path
```

It seems like this error comes from here.

https://github.com/tauri-apps/tauri-action/blob/32459febfda6db38ca59ec034f99ba8cdd500113/src/init-project.ts#L10-L28

`tauri init` is run after `const tauriPath = getTauriDir(root);`. Is it a bug?

**Comment by FabianLars** [comment]
you're right, the lines were swapped when i moved code around :/

thanks for the report 👍

**Comment by liudonghua123** [comment]
I updated the code and test again. However, it failed again without error info.

```
Run liudonghua1[2](https://github.com/liudonghua123/flutter_website/actions/runs/5077744130/jobs/9125113916#step:10:2)[3](https://github.com/liudonghua123/flutter_website/actions/runs/5077744130/jobs/9125113916#step:10:3)/tauri-action@dev
  with:
    distPath: _site
    tagName: flutter_website v__VERSION__
    releaseName: flutter.dev site v__VERSION__
    releaseBody: See the assets to download this version and install.
    bundleIdentifier: dev.flutter.site
    args: -c {"build":{"beforeBuildCommand":""},"package":{"productName":"flutter_website","version":"3.10.0"}}
    releaseDraft: false
    prerelease: false
    projectPath: .
    includeDebug: false
    includeRelease: true
    includeUpdaterJson: true
    updaterJsonKeepUniversal: false
  env:
    NODE_ENV: production
    NODE_VERSION: 18
    APP_NAME: flutter_website
    RELEASE_VERSION: 3.10.0
    JEKYLL_BUILD_DIR: _site
    GITHUB_TOKEN: ***
running npm [ 'install', '-g', '@tauri-apps/cli' ]

added 2 packages in [4](https://github.com/liudonghua123/flutter_website/actions/runs/5077744130/jobs/9125113916#step:10:4)s

1 package is looking for funding
  run `npm fund` for details
running tauri [ 'init', '--ci', '--app-name', 'docs.flutter.dev' ]
```

<img width="606" alt="image" src="https://github.com/tauri-apps/tauri-action/assets/2276718/e63e8808-2e33-48f1-9413-a17bfc1fb86d">
