### ISSUE TITLE
Error Invalid byte 34, offset 352.

### ISSUE THREAD

**Issue by Ekernik** [tauri-apps/tauri-action#480]
After I implemented updater I get this error during tauri-apps/tauri-action@v0.
Not sure where to look for a solution and what the problem is, as it looks like the building release finishes without errors.

 ```bash
Finished release [optimized] target(s) in 4m 54s
    Bundling my-app.app (/Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/macos/my-app.app)
    Bundling my-app_0.3.0_x64.dmg (/Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/dmg/my-app_0.3.0_x64.dmg)
     Running bundle_dmg.sh
    Bundling /Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/macos/my-app.app.tar.gz (/Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/macos/my-app.app.tar.gz)
    Finished 3 bundles at:
        /Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/macos/my-app.app
        /Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/dmg/my-app_0.3.0_x64.dmg
        /Users/runner/work/my-app/my-app/src-tauri/target/release/bundle/macos/my-app.app.tar.gz (updater)

       Error Invalid byte 34, offset 352.
 ELIFECYCLE  Command failed with exit code 1.
Error: Command failed with exit code 1: pnpm tauri build
``` 

I have set private key and key password in github secrets and pubkey in tauri.conf.json

Here is my build.yml script:

```yml
name: 'publish'
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
```
