### ISSUE TITLE
Builds on windows-latest failing

### ISSUE THREAD

**Issue by jackadair** [tauri-apps/tauri-action#500]
Recently returned to a project after about a month or so and my windows build is failing all of the sudden with no significant changes made. We can build successfully on hardware.

I'm receiving the following error:

![Screenshot 2023-06-16 at 9 29 41 AM](https://github.com/tauri-apps/tauri-action/assets/54963231/a163258e-0cb2-4255-87c3-c36c87cfcc20)

And here is my action:

```
name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "windows-latest"

    runs-on: ${{ matrix.settings.platform }}
    environment: Caspr-Releases
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - name: install app dependencies and build it
        run: npm install && npm run build
      - uses: tauri-apps/tauri-action@v0
        env:
          various secrets
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Caspr v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{matrix.settings.args}}
 ```

I've found this [Stack Overflow answer](https://stackoverflow.com/a/76173513/12763887)  that explains that it could have something to do with the tokio runtime version so if I could get some help setting that in our Tauri App that would be great!

Thanks
