### ISSUE TITLE
Building for x86_64 linux?

### ISSUE THREAD

**Issue by StelFoog** [tauri-apps/tauri-action#586]
I'm tying to build for x86_64 linux, but the released files are always marked with `arm64`. I have added

```toml
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
```

to `src-tauri/Cargo.toml` and

```yml
with:
  # other properties...
  args: ${{ matrix.platform == 'ubuntu-20.04' && '--target x86_64-unknown-linux-gnu' || '' }}
```
to `.github/workflows/release.yml` and can see that `tauri build --target x86_64-unknown-linux-gnu` is the command run during the build step but still no luck.

What configuration should I add to correctly build targeting x86?
