### ISSUE TITLE
[QUESTION] How do I build macos Intel and simultaneously Apple Silicon

### ISSUE THREAD

**Issue by Volankey** [tauri-apps/tauri-action#743]
How do I build macos Intel and simultaneously Apple Silicon in action

**Comment by venkr** [comment]
Pass `--target universal-apple-darwin` to args, and it will build a universal, ie: Intel + Apple Silicon build.

You will likely need to install the appropriate arch support before that:
```
      - name: Install Rust x86_64 Support (macOS)
        run: rustup target add x86_64-apple-darwin
```

**Comment by Volankey** [comment]
> Pass `--target universal-apple-darwin` to args, and it will build a universal, ie: Intel + Apple Silicon build.
> 
> You will likely need to install the appropriate arch support before that:
> 
> ```
>       - name: Install Rust x86_64 Support (macOS)
>         run: rustup target add x86_64-apple-darwin
> ```

Thanks Reply.
If you want to build `x86_64-apple-darwin` and `aarch64-apple-darwin`, you can refer to the following code,
```
jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          # - os: ubuntu-latest
          #   rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          # - os: windows-latest
          #   rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform.os }}
	steps:
		- name: Rustup add target
			run: rustup target add ${{ matrix.platform.rust_target }}
		- name: Build the app
			uses: tauri-apps/tauri-action@v0
			with:
				args: "--target ${{ matrix.platform.rust_target }}"
```
