### ISSUE TITLE
Windows AArch64

### ISSUE THREAD

**Issue by jiriqx** [tauri-apps/tauri-action#785]
I am trying to create a release for Windows x64 and AArch64, but when i run the action with these settings, only x64 builds show up in the release.

`matrix:
        include:
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc`

**Comment by FabianLars** [comment]
Did you actually apply the settings further down when the app is actually built? Feel free to post the full workflow so we can actually see what you're doing.

Edit: Also the logs of that "failed" workflow would be appreciated.

**Comment by jiriqx** [comment]
This my full workflow:

```
name: 'Tauri build and publish'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
```

Also, the workflow itself does not fail, it passes, but when I look into the release, there is no AArch64 build.

**Comment by FabianLars** [comment]
> Also, the workflow itself does not fail, it passes, but when I look into the release, there is no AArch64 build.

Yeah, got that already, but the logs are often still helpful (not in this case since the workflow shows the issue already).

Anyway, your workflow is missing 2 things, the rust toolchain, and the actual use of the setting i already hinted at in my first message.

```yml
name: 'Tauri build and publish'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc
# This ^

      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
# and this ^
```
