### ISSUE TITLE
Example in homepage causes problems with Target Triples and Sidecars

### ISSUE THREAD

**Issue by kareemmahlees** [tauri-apps/tauri-action#812]
## Description
While migrating my application to Tauri V2, I also updated my release actions to the example mentioned [here](https://github.com/tauri-apps/tauri-action#:~:text=your%20web%20app.-,Usage,-For%20more%20workflow).
Then I started to notice that the matrix with target `x86_64-apple-darwin` always fails to resolve the correct target triple ( it resolved to the same target triple as the first matrix ).

## Solution
By doing some research I found out that the target triple of the second matrix is of `macos-13`, and `macos-latest` resolves to `macos-14` which gives a completely different target triple.
```yaml
matrix:
        include:
          - platform: 'macos-latest' 
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-13' #< --- change this
            args: '--target x86_64-apple-darwin'
```
If this deserves a dedicated PR I am happy to help!
