### ISSUE TITLE
[Feature Request] Add option to generate `SHASUMS256.txt` file in `tauri-action`.

### ISSUE THREAD

**Issue by kjxbyz** [tauri-apps/tauri-action#851]
Generate `SHASUMS256.txt` file based on build assets, refer to https://nodejs.org/dist/v20.15.0/SHASUMS256.txt

**Comment by fu050409** [comment]
This feature is useful to me. But seems that no one take this issue for a long time, can I try to resolve it if okay?

**Comment by FabianLars** [comment]
yes, sure. Contributions are very welcome!

**Comment by kjxbyz** [comment]
You can use third-party tools to generate this file.

```
name: Release
on:
  workflow_dispatch:

permissions: read-all

jobs:
  gen_shasum:
    name: Gen Shasum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install ts-shasum
        run: npm install -g ts-shasum

      - name: Download assets
        uses: robinraju/release-downloader@v1
        with:
          tag: 
          fileName: '*'
          tarBall: false
          zipBall: false
          out-file-path: 'downloads'
      
      - name: Gen SHASUMS256.txt
        run: shasum create "$GITHUB_WORKSPACE/SHASUMS256.txt" *
        working-directory: ${{ github.workspace }}/downloads

      - name: Upload assets
        run: gh release upload "$TAG_NAME" ./SHASUMS256.txt
        env:
          TAG_NAME: 
          GH_TOKEN: 
```
