### ISSUE TITLE
debug build fails and does not create a release 

### ISSUE THREAD

**Issue by MarkusAtCoduct** [tauri-apps/tauri-action#868]
Hello everyone,

when I try to create a debug build using the github action, I get this error:

```
 Warn Signing, by default, is only supported on Windows hosts, but you can specify a custom signing command in `bundler > windows > sign_command`, for now, skipping signing the installer...
    Bundling projectName.app (/Users/runner/work/Tank_Vizualization_Shell/projectName/src-tauri/target/aarch64-apple-darwin/debug/bundle/macos/projectName.app)
    Bundling projectName_0.2.0_aarch64.dmg (/Users/runner/work/projectName/projectName/src-tauri/target/aarch64-apple-darwin/debug/bundle/dmg/projectName_0.2.0_aarch64.dmg)
     Running bundle_dmg.sh
    Finished 2 bundles at:
        /Users/runner/work/projectName/projectName/src-tauri/target/aarch64-apple-darwin/debug/bundle/macos/projectName.app
        /Users/runner/work/projectNamel/projectName/src-tauri/target/aarch64-apple-darwin/debug/bundle/dmg/projectName_0.2.0_aarch64.dmg

Done in 119.72s.
Error: No artifacts were found.
```

I have updated my workflow file to look like this :

```
name: 'publish'

on:
  push:
    branches:
      - release

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            includeDebug: true
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            includeDebug: true
            args: '--target x86_64-apple-darwin'
#          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
#            args: ''
#          - platform: 'windows-latest'
#            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeDebug: true
          args: ${{ matrix.args }}
```

any help is greatly apprecheated
