### ISSUE TITLE
Config arguments don't seem to work

### ISSUE THREAD

**Issue by rajatkulkarni95** [tauri-apps/tauri-action#879]
I'm trying to utilise a different `conf` file when building for linux, and when I do this

```
 with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "Octarine v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "Linux Build"
          releaseDraft: true
          prerelease: false
          args: "-c src-tauri/tauri.conf.linux.json"
```

or 

```
 with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "Octarine v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "Linux Build"
          releaseDraft: true
          prerelease: false
          args: "-c ./src-tauri/tauri.conf.linux.json"
```

it fails with this

```
Run tauri-apps/tauri-action@dev
Couldn't parse --config flag as inline JSON. This is not an error if it's a file path. Source: "Unexpected token 's', "src-tauri/"... is not valid JSON"
running pnpm [ 'tauri', 'build', '-c', 'src-tauri/tauri.conf.linux.json' ]

> octarine@0.16.1 tauri /home/runner/work/octarine/octarine
> tauri "build" "-c" "src-tauri/tauri.conf.linux.json"
```

**Comment by rajatkulkarni95** [comment]
Tried multiple combinations

```
          args: "--config tauri.conf.linux.json"
```

Moved the file outside and stuff, and it still doesn't take it.

This also leads to `Signature not found` i believe.

**Comment by FabianLars** [comment]
What you wrote in your original post should be correct. Can you add something really obvious to the extra config like a weird window config or a beforeBuildCommand that logs something?

**Comment by rajatkulkarni95** [comment]
> What you wrote in your original post should be correct. Can you add something really obvious to the extra config like a weird window config or a beforeBuildCommand that logs something?

You mean something that breaks it?

Here's an example of the path being wrong, and the action instantly fails, but when the path is right, it gives the same warning, but doesn't fail


<img width="1227" alt="Screenshot 2024-08-03 at 16 32 04" src="https://github.com/user-attachments/assets/1ecf5de3-4a73-4f09-a34a-0566011e0190">
<img width="1227" alt="Screenshot 2024-08-03 at 16 31 41" src="https://github.com/user-attachments/assets/85236abd-4136-4826-9716-744603d76f23">

**Comment by FabianLars** [comment]
> You mean something that breaks it?

Pretty much, yeah.

> Here's an example of the path being wrong, and the action instantly fails, but when the path is right, it gives the same warning, but doesn't fail

That sounds like it's working correctly then.

**Comment by rajatkulkarni95** [comment]
Also is there a reason why the `signature` doesn't get created in the action?
<img width="1183" alt="Screenshot 2024-08-03 at 16 34 36" src="https://github.com/user-attachments/assets/acaff44f-b22e-467f-a909-de7e45ec1b59">

Here's the tauri-conf

```
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "pnpm build",
    "beforeDevCommand": "pnpm dev",
    "frontendDist": "../dist",
    "devUrl": "http://localhost:2450"
  },
  "bundle": {
    "active": true,
    "category": "Productivity",
    "copyright": "",
    "targets": ["deb", "nsis", "msi", "app", "dmg"],
    "createUpdaterArtifacts": true,
    "externalBin": [],
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ],
    "windows": {
      "certificateThumbprint": null,
      "digestAlgorithm": "sha256",
      "timestampUrl": ""
    },
    "longDescription": "",
    "macOS": {
      "entitlements": null,
      "exceptionDomain": "",
      "frameworks": [],
      "providerShortName": null,
      "signingIdentity": null
    },
    "resources": [],
    "shortDescription": "",
    "linux": {
      "deb": {
        "depends": []
      }
    }
  },
  "productName": "Octarine",
  "version": "../package.json",
  "identifier": "Octarine",
  "plugins": {
    "updater": {
      "pubkey": "key here",
      "endpoints": [
        "endpoint here",
      ]
    }
  },
  "app": {
    "withGlobalTauri": false,
    "windows": [
      {
        "fullscreen": false,
        "height": 768,
        "resizable": true,
        "title": "",
        "width": 1280,
        "minHeight": 640,
        "minWidth": 480,
        "titleBarStyle": "Overlay",
        "dragDropEnabled": false
      }
    ],
    "security": {
      "assetProtocol": {
        "scope": {
          "allow": ["**"],
          "deny": [],
          "requireLiteralLeadingDot": false
        },
        "enable": true
      },
      "dangerousDisableAssetCspModification": true,
      "csp": "default-src 'self'; img-src 'self' asset: https://* data: blob:; media-src stream: https://* asset: https://*;  style-src 'self' 'unsafe-inline';; connect-src ipc: http://ipc.localhost"
    }
  }
}
```

**Comment by rajatkulkarni95** [comment]
But it does notarise and create signatures when I run `tauri build` locally on my mac.

**Comment by FabianLars** [comment]
Did you set up the updater private key? without it, the tauri cli will not build the updater artifacts (though i'd expect an error since you enabled the updater in tauri.conf.json)

**Comment by rajatkulkarni95** [comment]
> Did you set up the updater private key? without it, the tauri cli will not build the updater artifacts (though i'd expect an error since you enabled the updater in tauri.conf.json)

Yep, this is the action!

```
      - name: Build the app
        uses: tauri-apps/tauri-action@dev

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "Octarine v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "Linux Build"
          releaseDraft: true
          prerelease: false
```

The duplicates are due to v1 / v2 variable name changes
