### ISSUE TITLE
Tauri v2 rc github action build fail on ubuntu 22.04 : could not compile `windows_x86_64_msvc` (lib)

### ISSUE THREAD

**Issue by MosRat** [tauri-apps/tauri-action#891]
Version: Tauri v2 rc

Workflow
```yml
name: 'publish'

on:
  push:
    tags:
      - 'v*'


jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: install frontend dependencies
        run: pnpm install  --no-frozen-lockfile # change this to npm, pnpm or bun depending on which one you use.

      - name: Generate release tag (Unix)
        if: runner.os != 'Windows'
        id: generate_tag_unix
        run: echo "TAG=${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate release tag (Windows)
        if: runner.os == 'Windows'
        id: generate_tag_windows
        run: |
          $tag = "${env:GITHUB_RUN_NUMBER}-$($env:GITHUB_SHA.Substring(0,7))"
          echo "TAG=$tag" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tagName: app-v__VERSION__-${{ steps.generate_tag_windows.outputs.TAG }}${{ steps.generate_tag_unix.outputs.TAG }} # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
```

output logs:
```bash
   Compiling siphasher v0.3.11
   Compiling autocfg v1.3.0
   Compiling windows_x86_64_msvc v0.52.6
   Compiling serde v1.0.208

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-pc-windows-msvc`

   Compiling syn v1.0.109
   Compiling getrandom v0.1.16
   Compiling getrandom v0.2.15
For more information about this error, try `rustc --explain E0463`.
   Compiling rand_core v0.6.4
error: could not compile `windows_x86_64_msvc` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
    Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.
Error: Command failed with exit code 1: pnpm tauri build
```
cargo.toml
```toml
[lib]
name = "tauri_v2_vue_template_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
```
