### ISSUE TITLE
No releaseId or tagName provided, skipping all uploads... But they are provided

### ISSUE THREAD

**Issue by LeonBirkel** [tauri-apps/tauri-action#906]
Hey,
when executing the action with the intend to generate a release I get following log(only last line is intresting).
-> No releaseId or tagName provided, skipping all uploads...
I will also share my action, I provided both of them :/ 

```
  Finished `release` profile [optimized] target(s) in 5m 23s
        Warn Signing, by default, is only supported on Windows hosts, but you can specify a custom signing command in `bundler > windows > sign_command`, for now, skipping signing the installer...
    Bundling bastion_0.0.1_amd64.deb (/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/deb/bastion_0.0.1_amd64.deb)
    Bundling bastion-0.0.1-1.x86_64.rpm (/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/rpm/bastion-0.0.1-1.x86_64.rpm)
    Bundling bastion_0.0.1_amd64.AppImage (/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage)
    Bundling /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz (/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz)
    Finished 3 bundles at:
        /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/deb/bastion_0.0.1_amd64.deb
        /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/rpm/bastion-0.0.1-1.x86_64.rpm
        /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage
        /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz (updater)
    Finished 1 updater signature at:
        /home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz.sig
Looking for artifacts in:
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/deb/BASTION_0.0.1_amd64.deb
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/rpm/BASTION-0.0.1-1.x86_64.rpm
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/BASTION_0.0.1_amd64.AppImage
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/BASTION_0.0.1_amd64.AppImage.sig
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/BASTION_0.0.1_amd64.AppImage.tar.gz
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/BASTION_0.0.1_amd64.AppImage.tar.gz.sig
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/deb/bastion_0.0.1_amd64.deb
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/rpm/bastion-0.0.1-1.x86_64.rpm
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.sig
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz.sig
Found artifacts:
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/deb/bastion_0.0.1_amd64.deb
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/rpm/bastion-0.0.1-1.x86_64.rpm
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz
/home/runner/work/bastion-app/bastion-app/src-tauri/target/release/bundle/appimage/bastion_0.0.1_amd64.AppImage.tar.gz.sig
No releaseId or tagName provided, skipping all uploads...
```
Action:
```
name: "publish"

on:
  push:
    branches:
      - production

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # for Arm based macs (M1 and above).
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04. # ubuntu-22.04
            args: ""
          # - platform: "windows-latest"
          #   args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # libwebkit2gtk-4.1-dev
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY:  ${{ secrets.BASTION_KEY_PRIVATE }}
          TAURI_KEY_PASSWORD: ${{ secrets.BASTION_KEY_PASSWORD }} 
          SIGN: "1"
          SIGN_KEY: ${{ secrets.BASTION_SIGNING_KEY_PRIVATE }} 
          APPIMAGETOOL_SIGN_PASSPHRASE: ${{ secrets.APPIMAGETOOL_SIGN_PASSPHRASE }} 
          releaseId: v__VERSION__
          tagName: bastion-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "BASTION v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }} --verbose
  notify-webserver:
    runs-on: ubuntu-latest
    needs: publish-tauri  # Run only after the Tauri build is successful
    steps:
      - name: Trigger web server update (example)
        run: |
          curl -X POST https://bastion-software.com/api/app/version/new_release \
            -H "Content-Type: application/json" \
            -d '{"version": "${{ steps.publish-tauri.outputs.release_tag }}"}'
```

**Comment by FabianLars** [comment]
Your workflow is broken, all the tauri-action args were merged with `env` (env vars), it should look more like this
```yml
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY:  ${{ secrets.BASTION_KEY_PRIVATE }}
          TAURI_KEY_PASSWORD: ${{ secrets.BASTION_KEY_PASSWORD }} 
          SIGN: "1"
          SIGN_KEY: ${{ secrets.BASTION_SIGNING_KEY_PRIVATE }} 
          APPIMAGETOOL_SIGN_PASSPHRASE: ${{ secrets.APPIMAGETOOL_SIGN_PASSPHRASE }} 
        with: # <- THIS LINE
          releaseId: v__VERSION__
          tagName: bastion-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "BASTION v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }} --verbose
```
