### ISSUE TITLE
Duplicate Releases Sometimes Created

### ISSUE THREAD

**Issue by gschier** [tauri-apps/tauri-action#914]
Using the recommended setup, I sometimes get duplicate releases created for the same tag. Perhaps a race condition? 

This ends up with some artifacts uploading to one and other artifacts the other, requiring me to delete the releases and re-run the CI. Perhaps there's an atomic way to do the check/creation step?

Note: I thought this was a total fluke the first time it happened, but I've seen it 2 or 3 times now with https://github.com/yaakapp/app (78 releases)

**Comment by FabianLars** [comment]
> Perhaps there's an atomic way to do the check/creation step?

As far as i know, only by creating the release in a prior job: https://github.com/tauri-apps/tauri-action/blob/dev/examples/publish-to-manual-release.yml

I would still love to have some kind of workaround so not everyone needs to switch to multiple jobs but i'm out of (reasonable) ideas.

> Note: I thought this was a total fluke the first time it happened, but I've seen it 2 or 3 times now with [yaakapp/app](https://github.com/yaakapp/app) (78 releases)

Interesting, you're on first place then. You're also the second person reporting this in the last ~2 weeks. The last report before that was _years_ ago so i wonder if something changed on the server side (cause the action didn't change recently) 🤔

**Comment by gschier** [comment]
Yes, I wonder if it is indeed a server issue. I don't have any duplicates to look at right now but I do remember looking into it the first time it happened, expecting two platforms to have finished at a similar time, but they were minutes apart (I could be misremembering and will make sure to keep them around to debug, next time)

**Comment by dionysuzx** [comment]
I also have this issue. Just created two duplicate releases, and it's happened a few times before. 

I will add this: the time it just happened I ran the release twice. So it was doing two in parallel. I almost think it can't handle that and you need to do one release at a time...

**Comment by kasper9n** [comment]
I can't see what could possibly causes it, but I'm consistently getting duplicate releases.

<details><summary>release.yml</summary>

```yml
name: Release
on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.arg }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-latest, arg: --mac --x64, target: x86_64-apple-darwin }
          - { os: macos-latest, arg: --mac --arm64, target: aarch64-apple-darwin }
          - { os: ubuntu-latest, arg: --linux --x64, target: x86_64-unknown-linux-gnu }
          # - { os: ubuntu-latest, arg: --linux --arm64, target: aarch64-unknown-linux-gnu }
          - { os: windows-latest, arg: --windows --x64, target: x86_64-pc-windows-msvc }
          - { os: windows-latest, arg: --windows --arm64, target: aarch64-pc-windows-msvc }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: 'Install dependencies (Linux)'
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt-get install -y libwayland-dev pkg-config

      - run: npm install
      - run: npm run napi -- --target ${{ matrix.target }}
      - run: npm run build:web
      - run: npm run electron-builder -- ${{ matrix.arg }} --publish always --config.publish.provider github --config.publish.publishAutoUpdate false
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: npm run generate-update-json

      # Do not run in parallel - It can cause errors even with --clobber
      - name: Upload update.json
        if: matrix.target == 'aarch64-apple-darwin'
        run: gh release upload ${{ github.ref_name }} build/update.json
        env:
          GH_TOKEN: ${{ github.token }}
  release_android:
    runs-on: ubuntu-latest
    name: Android ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - { name: arm64, arch: aarch64, tauri_target: aarch64 }
          - { name: x64, arch: x86_64, tauri_target: x86_64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: JDK 17 Setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Android SDK Setup
        uses: android-actions/setup-android@v3

      - name: Android NDK Setup
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: Install Android targets
        run: rustup target add ${{ matrix.arch }}-linux-android

      - run: npm install
        working-directory: mobile

      - name: Android signing setup
        working-directory: mobile/src-tauri/gen/android
        run: |
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Get version
        run: echo "APP_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build
        # uploadWorkflowArtifacts and mobile are not released
        uses: tauri-apps/tauri-action@a1b01e690374452a209dd44f6de089dda9003d3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: mobile
          mobile: android
          tagName: v${{ env.APP_VERSION }}
          releaseName: ${{ env.APP_VERSION }}
          releaseDraft: true
          releaseAssetNamePattern: '[name]-v[version]-[platform]-[arch].[ext]'
          args: --apk --split-per-abi --target ${{ matrix.tauri_target }} --config '{"version":"${{ env.APP_VERSION }}"}'

```
</p>
</details> 


Example run: https://github.com/probablykasper/ferrum/actions/runs/22750231816

Electron first finishes it's builds first and creates a release.

<details><summary>Release now looks like this</summary>
<p>

<img width="590" height="409" alt="Image" src="https://github.com/user-attachments/assets/17f1fca2-1ff1-4765-a4ef-10c9686a73f6" />

</p>
</details>

Then Tauri android arm64 finishes, and uploads to the pre-existing release:
```
Fri, 06 Mar 2026 05:27:51 GMT Found artifacts:
Fri, 06 Mar 2026 05:27:51 GMT /home/runner/work/ferrum/ferrum/mobile/src-tauri/gen/android/app/build/outputs/apk/arm64/release/app-arm64-release.apk
Fri, 06 Mar 2026 05:27:51 GMT Looking for a draft release with tag v0.21.0...
Fri, 06 Mar 2026 05:27:52 GMT Found draft release with tag v0.21.0 on the release list.
Fri, 06 Mar 2026 05:27:52 GMT Updating name and body of existing release...
Fri, 06 Mar 2026 05:27:53 GMT Uploading app-arm64-release.apk...
Fri, 06 Mar 2026 05:27:54 GMT app-arm64-release.apk successfully ***ed.
Fri, 06 Mar 2026 05:27:54 GMT Signature not found for the updater JSON. Skipping ***...
```

<details><summary>Release now looks like this</summary>
<p>

<img width="1214" height="773" alt="Image" src="https://github.com/user-attachments/assets/f8a8d721-aaba-4c04-b717-e9eb06f8f5dd" />

</p>
</details>

Then Tauri android x64 finished, creating a new release because the old one no longer has the tag.

My best guess is that this for some senseless reason removes the tag
https://github.com/tauri-apps/tauri-action/blob/a1b01e690374452a209dd44f6de089dda9003d3d/src/create-release.ts#L142-L150
