### ISSUE TITLE
Don't push tag.

### ISSUE THREAD

**Issue by cathaysia** [tauri-apps/tauri-action#916]
I'm using this action for create a nightly release, but it seems this action must set `tagName`, `releaseId` and `releaseName` for release. And this action will push the new tag. How can I deny it push tag?

**Comment by FabianLars** [comment]
If you want it to keep pushing to the same release, simply set releaseId to the nightly release and omit tagName and releaseName

**Comment by FabianLars** [comment]
Alternatively, setting tagName and releaseName but also setting releaseComittish to a hardcoded commit sha may also work. 🤔

**Comment by cathaysia** [comment]
i tried this:

```yaml
- uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: 'Nightly'
          releaseDraft: false
          releaseId: Nightly
          prerelease: true
          args: ${{ matrix.args }}
```

but this action does not create a release， it tell me that:

> No releaseId or tagName provided, skipping all uploads...

Is this a bug?
