### ISSUE TITLE
Windows arm64 cross compilation support?

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri-action#952]
Is there a way to use this action on shared github runners to produce windows arm64 tauri binary/installer?

**Comment by FabianLars** [comment]
yes, in the os matrix at the top, add this
```yml
          - platform: "windows-latest"
            args: "--target aarch64-pc-windows-msvc"
```
and then also install the rust target. if you use our example you can modify it like this:
```yml
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin,aarch64-pc-windows-msvc
```

The github runner should have the OS dependencies that our guide mentions already installed, if not, or if you get any errors pleasse get back to me here.
