### ISSUE TITLE
Add files arg for custom assets files

### ISSUE THREAD

**Issue by M97Chahboun** [tauri-apps/tauri-action#984]
```yaml
with:
    tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
    args: ${{ matrix.args }}
    files: |
      path/app.apk
      other_path/other.apk
```
