### ISSUE TITLE
bun: not found Issue

### ISSUE THREAD

**Issue by Keshav-writes-code** [tauri-apps/tauri-action#986]
For Some Reason, when Runnig `tauri-apps/tauri-action@v0`, it uses `bun` for the build command which can not be found and errors

Error :
```sh
Run tauri-apps/tauri-action@v0
  
running npm [ 'run', 'tauri', 'build' ]
> tauri-app@0.1.0 tauri
> tauri build
    Running beforeBuildCommand `bun run build`
sh: 1: bun: not found
beforeBuildCommand `bun run build` failed with exit code 1[27](https://github.com/Keshav-writes-code/demo-tauri-app-linux-windows-android/actions/runs/12498616575/job/34872597488#step:7:28)
    Error beforeBuildCommand `bun run build` failed with exit code 127
Error: Command "npm ["run","tauri","build"]" failed with exit code 1
```

build.yml
```yml
name: "publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # using webkitgtk 4.1 is for Tauri v2.

      - name: install frontend dependencies
        run: npm install 

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          tauriScript: "npm run tauri"
          updaterJsonPreferNsis: true
          args: ${{ matrix.args }}
```
